### ISSUE TITLE
Parse 2016 general election precinct-level results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-sd#1]
If you want to work on a county, add a comment saying which one you'd like to work on or email openelections@gmail.com. You can either email us finished CSV files or submit a pull request, whatever is easiest. 

The results files you'll be converting can be found in our [sources repository](https://github.com/openelections/openelections-sources-sd/tree/master/2016). Many of these are either PDFs or Excel files, and in some cases you'll need to convert a number of office-specific files. For electronic PDFs, we recommend using [Tabula](http://tabula.technology/), which is free, to extract data. The goal is to create a single CSV file for each county, with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

For the following offices: President, U.S. Senate, U.S. House, State Senate, State House. You can use the [Miner County](https://github.com/openelections/openelections-data-sd/blob/master/2016/20161108__sd__general__miner__precinct.csv) file as an example of how things should look.

- [x] Aurora
- [x] Beadle
- [x] Bennett
- [x] Bon Homme
- [x] Brookings
- [x] Brown
- [x] Brule
- [x] Buffalo
- [x] Butte
- [x] Campbell
- [x] Charles Mix
- [x] Clark
- [x] Clay
- [x] Codington
- [x] Corson
- [x] Custer
- [x] Davison
- [x] Day
- [x] Deuel
- [x] Dewey
- [x] Douglas
- [x] Edmunds
- [x] Fall River
- [x] Faulk
- [x] Grant
- [x] Gregory
- [x] Haakon
- [x] Hamlin
- [x] Hand
- [x] Hanson
- [x] Harding
- [x] Hughes
- [x] Hutchinson
- [x] Hyde (single vote center county)
- [x] Jackson
- [x] Jerauld
- [x] Jones
- [x] Kingsbury
- [x] Lake
- [x] Lawrence
- [x] Lincoln
- [x] Lyman
- [x] Marshall
- [x] McCook
- [x] McPherson
- [x] Meade
- [x] Mellette
- [x] Miner
- [x] Minnehaha
- [x] Moody
- [x] Oglala Lakota
- [x] Pennington
- [x] Perkins
- [x] Potter
- [x] Roberts
- [x] Sanborn
- [x] Spink
- [x] Stanley
- [x] Sully
- [x] Todd
- [x] Tripp
- [x] Turner
- [x] Union
- [x] Walworth
- [x] Yankton
- [x] Ziebach

**Comment by jamesclarence** [comment]
I'll work on Aurora. Should be coming up shortly!

**Comment by jamesclarence** [comment]
I'll get Brule, Clark, and Clay (Clay is general and primary) next

**Comment by dwillis** [comment]
Awesome, thanks!

**Comment by lephead** [comment]
I see no one did Minnehaha yet.

**Comment by dwillis** [comment]
@lephead they are yours for the taking.
